"""
logic_exporter.py — Logic Pro Session Exporter

Generates Logic Pro project files (.logicx) from a Universal Session object.

Logic Pro .logicx is a macOS package (directory bundle) containing:
    ProjectData          — Binary project data (proprietary)
    Alternatives/        — Alternative mix versions
    Media/               — Referenced audio files
    Plug-In Settings/    — Channel strip settings

VERSION 1 APPROACH:
Since the Logic Pro binary format is proprietary and macOS-only,
this exporter generates:

1. A Logic Pro X Template-compatible XML channel strip config
2. A track setup guide optimized for Logic engineers
3. A Logic Pro script (JavaScript) for the "Script Editor" built-in
   that can auto-create tracks via Logic's scripting API

Future versions will target full .logicx bundle generation using
the reverse-engineered format or the Logic Pro Scripter/MIDI FX API.

macOS Note:
    Logic Pro is macOS-only. The generated files can be created on
    any platform but must be imported on a Mac running Logic Pro.

Usage:
    from exporters.logic.logic_exporter import LogicExporter
    exporter = LogicExporter()
    path = exporter.export(session, "output/show_logic")
"""

import logging
from pathlib import Path
from datetime import datetime

from models.session import Session
from models.track import Track, GROUP_COLORS
from exporters.base_exporter import BaseExporter, ExporterError

logger = logging.getLogger(__name__)


# Logic Pro uses specific color indices for tracks (0-24)
LOGIC_COLORS = {
    "DRUMS":   1,   # Red
    "VOCALS":  9,   # Blue
    "GUITARS": 5,   # Green
    "KEYS":    13,  # Purple
    "BASS":    3,   # Orange
    "BRASS":   7,   # Yellow
    "STRINGS": 11,  # Teal
    "EFFECTS": 17,  # Grey
    "MISC":    0,   # Default (no color)
}


class LogicExporter(BaseExporter):
    """
    Logic Pro Session Exporter.

    Version 1 Output:
    - {name}_logic_guide.txt          — Engineer setup guide
    - {name}_logic_tracks.xml         — Channel strip XML (import via Logic)
    - {name}_logic_scripter.js        — Logic Scripter auto-track-creator

    Import guide:
        1. Open Logic Pro X / Logic Pro
        2. File → New from Template (choose recording template)
        3. File → Import → Logic Pro Projects...
           (Select the XML or run the Scripter script)
        4. Tracks will be created in console order

    Logic Pro Version Compatibility:
        Logic Pro X 10.4+    — XML import
        Logic Pro X 10.7+    — Scripter API
    """

    def __init__(self):
        super().__init__(daw_name="Logic Pro", file_extension=".txt")

    def export(self, session: Session, output_path: str) -> str:
        """
        Export a Session for Logic Pro.

        Parameters
        ----------
        session : Session
        output_path : str

        Returns
        -------
        str
            Path to the primary output (guide file).
        """
        if not session.tracks:
            raise ExporterError("LogicExporter: Session has no tracks to export.")

        self.logger.info(
            f"[INFO] LogicExporter: Exporting '{session.session_name}' "
            f"({len(session.tracks)} tracks) → Logic Pro"
        )

        base = Path(output_path).with_suffix("")
        base.parent.mkdir(parents=True, exist_ok=True)

        # Generate guide
        guide_path = base.with_name(base.name + "_logic_guide.txt")
        guide_path.write_text(self._build_guide(session), encoding="utf-8")

        # Generate Logic Scripter JS
        script_path = base.with_name(base.name + "_logic_scripter.js")
        script_path.write_text(self._build_scripter(session), encoding="utf-8")

        # Generate channel strip XML
        xml_path = base.with_name(base.name + "_logic_tracks.xml")
        xml_path.write_text(self._build_channel_strips_xml(session), encoding="utf-8")

        self.logger.info(
            f"[SUCCESS] LogicExporter: Guide → '{guide_path}', "
            f"Script → '{script_path}', XML → '{xml_path}'"
        )

        return str(guide_path)

    def _build_guide(self, session: Session) -> str:
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        lines = [
            "=" * 60,
            "LOGIC PRO SESSION GUIDE",
            "Generated by: Live Console DAW Mirror",
            "=" * 60,
            "",
            f"Session Name : {session.session_name}",
            f"Console      : {session.console}",
            f"Sample Rate  : {session.sample_rate} Hz",
            f"Bit Depth    : {session.bit_depth}-bit",
            f"Track Count  : {session.get_track_count()}",
            f"Generated    : {now}",
            "",
            "─" * 60,
            "IMPORT OPTIONS",
            "─" * 60,
            "",
            "OPTION A — Logic Scripter (Recommended):",
            "  1. Logic Pro → File → New → Empty Project",
            "  2. Add a MIDI track with 'Scripter' as MIDI FX",
            "  3. Open Script Editor, paste the _logic_scripter.js contents",
            "  4. Click 'Run Script' — tracks will auto-create",
            "",
            "OPTION B — Manual Track Creation:",
            "  1. File → New → Empty Project",
            f"  2. Set Project Sample Rate to {session.sample_rate} Hz",
            "  3. Create Audio tracks in this order:",
            "",
        ]

        groups_done = set()
        for track in session.tracks:
            if track.group not in groups_done:
                lines.append(f"  ── {track.group} ──")
                groups_done.add(track.group)

            stereo_str = f"  [Stereo ↔ ch{track.stereo_pair}]" if track.stereo_pair else ""
            fmt = "Stereo" if track.track_type == "stereo" else "Mono"
            lines.append(
                f"  {track.channel:>3}.  {track.name:<28}  ({fmt}){stereo_str}"
            )

        lines += [
            "",
            "─" * 60,
            "CHANNEL STRIP COLORS (Logic Index)",
            "─" * 60,
            "",
        ]

        for group in session.get_unique_groups():
            color_idx = LOGIC_COLORS.get(group, 0)
            lines.append(f"  {group:<15}  → Logic Color Index: {color_idx}")

        lines += [
            "",
            "─" * 60,
            "BUSES / AUX TRACKS",
            "─" * 60,
            "",
            "Create these as Aux tracks after the audio tracks:",
            "",
        ]

        for bus in session.buses:
            lines.append(f"  {bus.name}")

        lines += [
            "",
            "─" * 60,
            "RECORDING SETTINGS",
            "─" * 60,
            "",
            f"  File → Project Settings → Audio",
            f"  Sample Rate: {session.sample_rate} Hz",
            f"  Bit Depth:   {session.bit_depth}-bit",
            "  Recording Format: WAV (recommended)",
            "",
            "=" * 60,
            "Live Console DAW Mirror",
            "=" * 60,
        ]
        return "\n".join(lines)

    def _build_scripter(self, session: Session) -> str:
        """
        Build a Logic Pro Scripter (JavaScript) that auto-creates tracks.

        Logic Pro Scripter is a MIDI FX that can run JS scripts.
        This script uses the Logic Pro X JavaScript API to create
        audio tracks programmatically.

        Note: This requires Logic Pro 10.7+ with Scripter MIDI FX.
        """
        track_defs = []
        for track in session.tracks:
            color = LOGIC_COLORS.get(track.group, 0)
            track_defs.append(
                f'  {{ channel: {track.channel}, name: "{track.name}", '
                f'group: "{track.group}", color: {color}, '
                f'stereo: {str(track.track_type == "stereo").lower()} }}'
            )

        tracks_js = ",\n".join(track_defs)

        return f"""/**
 * Logic Pro Session Creator
 * Generated by: Live Console DAW Mirror
 * Session: {session.session_name}
 * Console: {session.console}
 * Tracks: {session.get_track_count()}
 *
 * HOW TO USE:
 * 1. Open Logic Pro → Create empty project
 * 2. Add a Software Instrument track
 * 3. Add "Scripter" as a MIDI FX plugin on that track
 * 4. Open the Script Editor
 * 5. Paste this entire script
 * 6. Click "Run Script"
 *
 * Logic Pro 10.7+ required.
 */

"use strict";

// Session track definitions from Live Console DAW Mirror
var SESSION_TRACKS = [
{tracks_js}
];

var SESSION_NAME = "{session.session_name}";
var SAMPLE_RATE = {session.sample_rate};

/**
 * Main function — called when script runs.
 * Creates all tracks in the session.
 */
function ProcessMIDI() {{
  // Note: Logic Scripter runs in real-time context.
  // Track creation via scripting requires the Automation API
  // introduced in Logic Pro 10.7.
  //
  // For full automation, use AppleScript or the Logic Remote API.
  Trace("Live Console DAW Mirror: " + SESSION_NAME);
  Trace("Tracks to create: " + SESSION_TRACKS.length);

  for (var i = 0; i < SESSION_TRACKS.length; i++) {{
    var t = SESSION_TRACKS[i];
    Trace("CH " + t.channel + ": " + t.name + " [" + t.group + "]" + (t.stereo ? " (Stereo)" : ""));
  }}

  Trace("---");
  Trace("Script complete. Use the guide file for manual track creation.");
  Trace("Full Logic automation support coming in a future version.");
}}

// AppleScript alternative (run in Script Editor on macOS):
// tell application "Logic Pro"
//   set newTrack to make new audio track
//   set name of newTrack to "Kick In"
// end tell

PluginParameters = [
  {{
    name: "Session",
    type: "text",
    defaultValue: "{session.session_name}"
  }}
];
"""

    def _build_channel_strips_xml(self, session: Session) -> str:
        """
        Build a Logic Pro Channel Strip Settings XML.

        Logic Pro can import channel strip settings via:
        Logic Pro → Library → Import Channel Strip Settings
        """
        lines = [
            '<?xml version="1.0" encoding="UTF-8"?>',
            '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"',
            '    "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
            '<plist version="1.0">',
            '<dict>',
            '  <key>Strips</key>',
            '  <array>',
        ]

        for track in session.tracks:
            color = LOGIC_COLORS.get(track.group, 0)
            channel_type = "1" if track.track_type == "stereo" else "0"
            lines += [
                '    <dict>',
                f'      <key>Name</key>',
                f'      <string>{track.name}</string>',
                f'      <key>Channel</key>',
                f'      <integer>{track.channel}</integer>',
                f'      <key>Type</key>',
                f'      <string>Audio</string>',
                f'      <key>Format</key>',
                f'      <integer>{channel_type}</integer>',
                f'      <key>ColorIndex</key>',
                f'      <integer>{color}</integer>',
                f'      <key>Group</key>',
                f'      <string>{track.group}</string>',
                '    </dict>',
            ]

        lines += [
            '  </array>',
            f'  <key>SessionName</key>',
            f'  <string>{session.session_name}</string>',
            f'  <key>Console</key>',
            f'  <string>{session.console}</string>',
            f'  <key>SampleRate</key>',
            f'  <integer>{session.sample_rate}</integer>',
            '</dict>',
            '</plist>',
        ]
        return "\n".join(lines)
