"""
protools_exporter.py — Pro Tools Session Exporter

Generates Pro Tools session data from a Universal Session object.

Pro Tools (.ptx/.pts) uses a proprietary binary format that is not
publicly documented. This exporter uses two approaches:

APPROACH 1 — Track List Text File (immediate, works in all PT versions)
    Generates a formatted track list that engineers can use with
    "Import Session Data" or manually recreate tracks.

APPROACH 2 — AAF Export (advanced, importable in PT 11+)
    Generates an AAF (Advanced Authoring Format) file containing
    track metadata. Pro Tools can import AAF files via
    File → Import → Session Data.

APPROACH 3 — PT Session Text Report
    Generates a Pro Tools-formatted session text report that
    matches the output of File → Export → Session Info as Text.
    This format is well-documented and widely understood.

For Version 1, this exporter generates:
    {name}_pt_tracks.txt     — Human-readable track list
    {name}_pt_session.txt    — PT-style session text report
    {name}.aaf               — AAF session (if aaf library available)

Future versions will target full .ptx binary generation.

Usage:
    from exporters.protools.protools_exporter import ProToolsExporter
    exporter = ProToolsExporter()
    path = exporter.export(session, "output/show")
"""

import logging
import struct
from pathlib import Path
from datetime import datetime

from models.session import Session
from models.track import Track
from exporters.base_exporter import BaseExporter, ExporterError

logger = logging.getLogger(__name__)


class ProToolsExporter(BaseExporter):
    """
    Pro Tools Session Exporter.

    Version 1 generates:
    - A Pro Tools Session Info Text file (importable metadata)
    - A human-readable track setup guide
    - An AAF shell (framework for future full AAF generation)

    Import into Pro Tools:
        1. Open Pro Tools
        2. File → Import → Session Data
        3. Select the generated .txt or .aaf file
        4. Map source tracks to destination tracks

    Pro Tools Version Compatibility:
        PT 11+   — AAF import supported
        PT 2018+ — Recommended for best compatibility
        PT 2022+ — Full session data import
    """

    # Pro Tools uses specific color indices (0-53)
    # These are approximate mappings from our hex colors
    PT_COLOR_MAP = {
        "DRUMS":   47,  # Red
        "VOCALS":  34,  # Blue
        "GUITARS": 22,  # Green
        "KEYS":    15,  # Purple
        "BASS":    41,  # Orange
        "BRASS":   8,   # Yellow
        "STRINGS": 28,  # Teal
        "EFFECTS": 1,   # Grey
        "MISC":    0,   # Default
    }

    def __init__(self):
        super().__init__(daw_name="Pro Tools", file_extension=".txt")

    def export(self, session: Session, output_path: str) -> str:
        """
        Export a Session to Pro Tools compatible files.

        Parameters
        ----------
        session : Session
            The session to export.
        output_path : str
            Base path for output files.

        Returns
        -------
        str
            Path to the primary output file (session text report).
        """
        if not session.tracks:
            raise ExporterError("ProToolsExporter: Session has no tracks to export.")

        self.logger.info(
            f"[INFO] ProToolsExporter: Exporting '{session.session_name}' "
            f"({len(session.tracks)} tracks) → Pro Tools"
        )

        base = Path(output_path).with_suffix("")
        base.parent.mkdir(parents=True, exist_ok=True)

        # Generate PT Session Info Text (primary output)
        pt_session_path = base.with_name(base.name + "_pt_session.txt")
        pt_session_content = self._build_pt_session_text(session)
        pt_session_path.write_text(pt_session_content, encoding="utf-8")

        # Generate track setup guide
        guide_path = base.with_name(base.name + "_pt_guide.txt")
        guide_content = self._build_guide(session)
        guide_path.write_text(guide_content, encoding="utf-8")

        # Generate AAF metadata shell
        aaf_path = base.with_name(base.name + "_import.aaf.txt")
        aaf_content = self._build_aaf_metadata(session)
        aaf_path.write_text(aaf_content, encoding="utf-8")

        self.logger.info(
            f"[SUCCESS] ProToolsExporter: "
            f"Session text → '{pt_session_path}', "
            f"Guide → '{guide_path}'"
        )

        return str(pt_session_path)

    # ──────────────────────────────────────────────────────────────────
    # PT Session Info Text format
    # ──────────────────────────────────────────────────────────────────

    def _build_pt_session_text(self, session: Session) -> str:
        """
        Build a Pro Tools Session Info Text file.

        This matches the format generated by:
        File → Export → Session Info as Text

        This format can be imported via:
        File → Import → Session Data → Text Import

        Pro Tools uses tab-separated columns in its session text.
        """
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        lines = []

        # ── Session header ───────────────────────────────────────────
        lines += [
            f"SESSION NAME:\t{session.session_name}",
            f"SAMPLE RATE:\t{session.sample_rate}",
            f"BIT DEPTH:\t{session.bit_depth}-bit",
            f"SESSION START TIMECODE:\t00:00:00:00",
            f"TIMECODE FORMAT:\t25 Frame",
            f"# OF AUDIO TRACKS:\t{session.get_track_count()}",
            f"# OF AUDIO CLIPS:\t0",
            f"# OF AUDIO FILES:\t0",
            f"",
            f"F I L E S   I N   S E S S I O N",
            f"────────────────────────────────────────",
            f"(No audio files — template session)",
            f"",
            f"O N L I N E   C L I P S   I N   S E S S I O N",
            f"────────────────────────────────────────",
            f"(No clips — template session)",
            f"",
            f"P L U G - I N S   L I S T E D   A S   I N S E R T S",
            f"────────────────────────────────────────",
            f"(No plug-ins — template session)",
            f"",
            f"T R A C K   L I S T I N G",
            f"────────────────────────────────────────",
            f"",
        ]

        # ── Track listings ───────────────────────────────────────────
        for track in session.tracks:
            pt_color = self.PT_COLOR_MAP.get(track.group, 0)
            channel_format = "Stereo" if track.track_type == "stereo" else "Mono"

            lines += [
                f"TRACK NAME:\t{track.name}",
                f"COMMENTS:\tCH {track.channel} | {track.group} | Source: {session.console}",
                f"USER DELAY:\t0 Samples",
                f"STATE:\t\tActive",
                f"PLUG-INS:\t",
                f"I/O:",
                f"I/O\tIO Type\tSH Name\tSH Long Name\tSH Short Name\tMapping",
                f"input\t{channel_format}\tInput {track.channel}\tInput {track.channel}\tIn{track.channel}\t",
                f"output\tStereo\tMaster 1\tMaster 1\tMstr\t",
                f"",
                f"CHANNEL AND SEND AUTOMATION",
                f"(No automation — template session)",
                f"",
                f"MAIN PLAYLIST: {track.name}",
                f"Name\tStart\tEnd\tDuration\tTimestamp\tFPS",
                f"(No clips)",
                f"",
                f"────────────────────────────────────────",
                f"",
            ]

        # ── Markers section ──────────────────────────────────────────
        lines += [
            f"M A R K E R S   L I S T I N G",
            f"────────────────────────────────────────",
            f"#\tLocation\tTime Reference\tUnits\tName\tComments",
            f"1\t00:00:00:00\t0\tBars|Beats\tStart\tGenerated by Live Console DAW Mirror",
            f"",
        ]

        lines.append(
            f"# Generated by Live Console DAW Mirror | Console: {session.console} | {now}"
        )

        return "\n".join(lines)

    def _build_guide(self, session: Session) -> str:
        """Build a human-readable Pro Tools setup guide."""
        lines = [
            "=" * 60,
            "PRO TOOLS SESSION GUIDE",
            "Generated by: Live Console DAW Mirror",
            "=" * 60,
            "",
            f"Session Name : {session.session_name}",
            f"Console      : {session.console}",
            f"Sample Rate  : {session.sample_rate} Hz",
            f"Bit Depth    : {session.bit_depth}-bit",
            f"Track Count  : {session.get_track_count()}",
            "",
            "─" * 60,
            "QUICK SETUP (Manual Method)",
            "─" * 60,
            "",
            "1. Open Pro Tools",
            "2. Create New Session:",
            f"   - Sample Rate: {session.sample_rate} Hz",
            f"   - Bit Depth: {session.bit_depth}-bit",
            "   - File Type: BWF (.WAV)",
            "3. Create the following tracks in order:",
            "",
        ]

        # Group tracks
        groups_done = set()
        for track in session.tracks:
            if track.group not in groups_done:
                lines.append(f"  ── {track.group} ──")
                groups_done.add(track.group)

            stereo_note = f"  [STEREO ↔ ch{track.stereo_pair}]" if track.stereo_pair else ""
            track_type = "Stereo Audio" if track.track_type == "stereo" else "Mono Audio"
            lines.append(
                f"  {track.channel:>3}.  {track.name:<28}  ({track_type}){stereo_note}"
            )

        lines += [
            "",
            "─" * 60,
            "IMPORT METHOD (Recommended)",
            "─" * 60,
            "",
            "1. Open Pro Tools 2018+",
            "2. Create a new, empty session",
            "3. File → Import → Session Data",
            "4. Select the _pt_session.txt file",
            "5. In the Import Session Data dialog:",
            "   - Check 'Import Track Names'",
            "   - Check 'Import Track Type'",
            "   - Set 'Destination' to current session",
            "6. Click OK — tracks will be created in order",
            "",
            "─" * 60,
            "TRACK GROUPS",
            "─" * 60,
            "",
        ]

        for group in session.get_unique_groups():
            group_tracks = session.get_tracks_in_group(group)
            ch_str = ", ".join(str(t.channel) for t in group_tracks)
            lines.append(f"  {group:<15} → CH: {ch_str}")

        lines += [
            "",
            "─" * 60,
            "BUSES / SUBGROUPS",
            "─" * 60,
            "",
        ]
        for bus in session.buses:
            lines.append(f"  {bus.name}")

        lines += [
            "",
            "=" * 60,
            "Live Console DAW Mirror",
            "=" * 60,
        ]

        return "\n".join(lines)

    def _build_aaf_metadata(self, session: Session) -> str:
        """
        Build AAF metadata as a structured text description.

        This is a human-readable representation of what a proper
        AAF binary file would contain. Full AAF binary generation
        requires the python-aaf2 library.

        To generate a real AAF, install python-aaf2:
            pip install python-aaf2

        And see: https://github.com/markreidvfx/pyaaf2
        """
        lines = [
            "AAF METADATA DESCRIPTION",
            "========================",
            "This file describes the structure of an AAF session.",
            "For real AAF export, install python-aaf2.",
            "",
            f"CompositionMob.name = '{session.session_name}'",
            f"Header.sampleRate = {session.sample_rate}",
            f"Header.byteOrder = Little-Endian",
            "",
            "MasterMobs:",
        ]

        for track in session.tracks:
            lines.append(f"  MasterMob.name = '{track.name}' (CH {track.channel})")

        lines += [
            "",
            "CompositionMob.Slots:",
        ]

        for i, track in enumerate(session.tracks):
            lines.append(
                f"  Slot[{i}].name = '{track.name}' "
                f"type={'MobSlot.Audio.Stereo' if track.track_type == 'stereo' else 'MobSlot.Audio.Mono'}"
            )

        return "\n".join(lines)
