"""
nuendo_exporter.py — Nuendo Session Exporter

Nuendo uses the same Track Archive XML format as Cubase.
This exporter inherits the full Cubase exporter and overrides
only the guide text to be Nuendo-specific.

Tested with: Nuendo 12, 13

Import in Nuendo:
    File → Import → Track Archive → select the .xml file
"""

import logging
from exporters.cubase.cubase_exporter import CubaseExporter
from models.session import Session

logger = logging.getLogger(__name__)


class NuendoExporter(CubaseExporter):
    """
    Nuendo Session Exporter.

    Produces a Track Archive XML file identical to the Cubase exporter —
    Nuendo and Cubase share the same file format.

    The guide file is labeled for Nuendo workflow.
    """

    def __init__(self):
        super().__init__()
        self.daw_name = "Nuendo"

    def _build_guide(self, session: Session) -> str:
        """Override to produce a Nuendo-labeled guide."""
        lines = [
            "=" * 60,
            "NUENDO TRACK ARCHIVE IMPORT GUIDE",
            "Generated by: Live Console → DAW Mirror",
            "=" * 60,
            "",
            f"Session Name : {session.session_name}",
            f"Console      : {session.console}",
            f"Sample Rate  : {session.sample_rate} Hz",
            f"Bit Depth    : {session.bit_depth}-bit",
            f"Track Count  : {session.get_track_count()}",
            "",
            "─" * 60,
            "HOW TO IMPORT",
            "─" * 60,
            "",
            "1. Open Nuendo 12 or later",
            "2. Create a new empty project",
            f"   Set project sample rate to {session.sample_rate} Hz",
            "3. File → Import → Track Archive",
            "4. Select the .xml file next to this guide",
            "5. Click OK in the Import Options dialog",
            "6. All tracks appear in console channel order",
            "7. Route hardware inputs in the MixConsole",
            "",
            "─" * 60,
            "TRACK LIST",
            "─" * 60,
            "",
        ]
        prev = None
        for t in session.tracks:
            if t.group != prev:
                lines.append(f"  ── {t.group} ──")
                prev = t.group
            s = f"  ↔ ch{t.stereo_pair}" if t.stereo_pair else ""
            lines.append(f"  {t.channel:>3}  {t.name:<30} {t.track_type}{s}")
        lines += [
            "",
            "─" * 60,
            "NUENDO-SPECIFIC NOTES",
            "─" * 60,
            "",
            "• Nuendo supports all Cubase Track Archive features",
            "• For post-production workflows, set ADR/Dialogue bus routing",
            "  after import in the MixConsole",
            "• Consider using Nuendo's Scene/Take Manager for live recordings",
            "",
            "=" * 60,
            "Live Console → DAW Mirror",
            "=" * 60,
        ]
        return "\n".join(lines)
